# Generated by Django 5.2.13 on 2026-04-28 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.PositiveIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='waiting', max_length=12)),
                ('is_urgent', models.BooleanField(default=False)),
                ('schedule_start', models.DateTimeField(blank=True, null=True)),
                ('schedule_end', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('remark', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
    ]
