# Generated by Django 5.2.13 on 2026-04-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='waiting', max_length=12),
        ),
    ]
