# Generated by Django 5.2.13 on 2026-04-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lot_id',
            field=models.CharField(blank=True, default='', help_text='Wafer lot ID for tracking', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
