# Generated by Django 5.2.14 on 2026-05-19 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderstage_recipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orders.orderstage')),
            ],
            options={
                'db_table': 'approval',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['stage', '-decided_at'], name='approval_stage_i_01b5cd_idx'), models.Index(fields=['actor', '-decided_at'], name='approval_actor_i_b8b295_idx'), models.Index(fields=['decision', '-decided_at'], name='approval_decisio_8237f2_idx')],
            },
        ),
    ]
