# Generated by Django 5.2.14 on 2026-05-19 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderstage_received_at_orderstage_received_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_code', models.CharField(help_text='Suffix identifying this WIP group (e.g. "A", "B").', max_length=40)),
                ('wafer_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='orders.order')),
                ('parent_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='orders.sample')),
            ],
            options={
                'db_table': 'sample',
                'ordering': ['order', 'sub_code'],
                'indexes': [models.Index(fields=['order', 'sub_code'], name='sample_order_i_673481_idx'), models.Index(fields=['parent_sample'], name='sample_parent__8cf011_idx')],
                'unique_together': {('order', 'sub_code')},
            },
        ),
    ]
