# Generated by Django 5.2.14 on 2026-05-20 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['order', 'execution_order', 'sub_code']},
        ),
        migrations.AddField(
            model_name='orderstage',
            name='parameter_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sample',
            name='execution_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderstage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['order', 'execution_order'], name='sample_order_i_3d3422_idx'),
        ),
    ]
