# Generated by Django 5.2.13 on 2026-05-03 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('http_method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp'], name='activity_lo_timesta_3ab8d3_idx'), models.Index(fields=['user', '-timestamp'], name='activity_lo_user_id_7a9103_idx'), models.Index(fields=['action_type', '-timestamp'], name='activity_lo_action__9d3d97_idx')],
            },
        ),
    ]
