# Generated by Django 5.2.14 on 2026-05-19 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_recipe'),
        ('monitoring', '0002_activitylog_request_id'),
        ('orders', '0013_orderstage_received_at_orderstage_received_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('kind', models.CharField(choices=[('order_received', 'Order received'), ('order_signed_off', 'Order signed off'), ('order_scheduled', 'Order scheduled'), ('order_rejected', 'Order rejected'), ('order_completed', 'Order completed'), ('equipment_alert', 'Equipment alert'), ('system', 'System')], db_index=True, default='system', max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='equipments.equipment')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
                ('related_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.orderstage')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_31a7e3_idx'), models.Index(fields=['kind', '-created_at'], name='notificatio_kind_997e03_idx'), models.Index(fields=['level', '-created_at'], name='notificatio_level_0e5d12_idx')],
            },
        ),
    ]
