# Generated by Django 5.2.13 on 2026-04-28 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='equipments.equipment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='orders.order')),
            ],
            options={
                'db_table': 'equipment_booking',
                'indexes': [models.Index(fields=['equipment', 'started_at', 'ended_at'], name='equipment_b_equipme_5de7e2_idx')],
            },
        ),
    ]
