# Generated by Django 5.2.14 on 2026-05-19 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_recipe'),
        ('orders', '0011_orderstage_recipe'),
        ('scheduling', '0002_equipmentbooking_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('load', 'Load'), ('unload', 'Unload'), ('abort', 'Abort'), ('note', 'Note')], max_length=16)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('measurement', models.JSONField(blank=True, default=dict)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to='equipments.equipment')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to='equipments.recipe')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.orderstage')),
            ],
            options={
                'db_table': 'stage_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['stage', '-occurred_at'], name='stage_event_stage_i_29c8ab_idx'), models.Index(fields=['equipment', '-occurred_at'], name='stage_event_equipme_b4cb19_idx'), models.Index(fields=['event_type', '-occurred_at'], name='stage_event_event_t_2a9f97_idx')],
            },
        ),
    ]
