# Generated by Django 5.2.14 on 2026-05-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_stageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageevent',
            name='event_type',
            field=models.CharField(choices=[('receive', 'Receive'), ('load', 'Load'), ('unload', 'Unload'), ('abort', 'Abort'), ('note', 'Note')], max_length=16),
        ),
    ]
