# Generated by Django 5.2.14 on 2026-05-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_stageevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageevent',
            name='event_type',
            field=models.CharField(choices=[('receive', 'Receive'), ('split', 'Split'), ('dispatch', 'Dispatch'), ('set_parameters', 'Set Parameters'), ('assign', 'Assign'), ('load', 'Load'), ('unload', 'Unload'), ('abort', 'Abort'), ('note', 'Note')], max_length=16),
        ),
    ]
