# Generated by Django 5.2.13 on 2026-04-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='users.department'),
        ),
        migrations.AddField(
            model_name='experimentrequiredequipment',
            name='step_order',
            field=models.PositiveIntegerField(default=1, help_text='Order of this step in the experiment relay'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('pending', 'Pending'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=12),
        ),
    ]
