# Generated by Django 5.2.14 on 2026-05-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_wafer_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lab_specialty',
            field=models.CharField(choices=[('coord', 'Lot Coordinator (分貨)'), ('dispatcher', 'Dispatcher (派工)'), ('engineer', 'Process Engineer (設定參數)'), ('operator', 'Tool Operator (機台執行)'), ('none', 'No specialty')], default='none', max_length=20),
        ),
    ]
